// Code generated by ent, DO NOT EDIT.

package taskdependency

import (
	"taskai/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldLTE(FieldID, id))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v int64) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldEQ(FieldTaskID, v))
}

// DependsOnID applies equality check predicate on the "depends_on_id" field. It's identical to DependsOnIDEQ.
func DependsOnID(v int64) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldEQ(FieldDependsOnID, v))
}

// DependencyType applies equality check predicate on the "dependency_type" field. It's identical to DependencyTypeEQ.
func DependencyType(v string) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldEQ(FieldDependencyType, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldEQ(FieldCreatedAt, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v int64) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v int64) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...int64) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...int64) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldNotIn(FieldTaskID, vs...))
}

// DependsOnIDEQ applies the EQ predicate on the "depends_on_id" field.
func DependsOnIDEQ(v int64) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldEQ(FieldDependsOnID, v))
}

// DependsOnIDNEQ applies the NEQ predicate on the "depends_on_id" field.
func DependsOnIDNEQ(v int64) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldNEQ(FieldDependsOnID, v))
}

// DependsOnIDIn applies the In predicate on the "depends_on_id" field.
func DependsOnIDIn(vs ...int64) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldIn(FieldDependsOnID, vs...))
}

// DependsOnIDNotIn applies the NotIn predicate on the "depends_on_id" field.
func DependsOnIDNotIn(vs ...int64) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldNotIn(FieldDependsOnID, vs...))
}

// DependencyTypeEQ applies the EQ predicate on the "dependency_type" field.
func DependencyTypeEQ(v string) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldEQ(FieldDependencyType, v))
}

// DependencyTypeNEQ applies the NEQ predicate on the "dependency_type" field.
func DependencyTypeNEQ(v string) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldNEQ(FieldDependencyType, v))
}

// DependencyTypeIn applies the In predicate on the "dependency_type" field.
func DependencyTypeIn(vs ...string) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldIn(FieldDependencyType, vs...))
}

// DependencyTypeNotIn applies the NotIn predicate on the "dependency_type" field.
func DependencyTypeNotIn(vs ...string) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldNotIn(FieldDependencyType, vs...))
}

// DependencyTypeGT applies the GT predicate on the "dependency_type" field.
func DependencyTypeGT(v string) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldGT(FieldDependencyType, v))
}

// DependencyTypeGTE applies the GTE predicate on the "dependency_type" field.
func DependencyTypeGTE(v string) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldGTE(FieldDependencyType, v))
}

// DependencyTypeLT applies the LT predicate on the "dependency_type" field.
func DependencyTypeLT(v string) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldLT(FieldDependencyType, v))
}

// DependencyTypeLTE applies the LTE predicate on the "dependency_type" field.
func DependencyTypeLTE(v string) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldLTE(FieldDependencyType, v))
}

// DependencyTypeContains applies the Contains predicate on the "dependency_type" field.
func DependencyTypeContains(v string) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldContains(FieldDependencyType, v))
}

// DependencyTypeHasPrefix applies the HasPrefix predicate on the "dependency_type" field.
func DependencyTypeHasPrefix(v string) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldHasPrefix(FieldDependencyType, v))
}

// DependencyTypeHasSuffix applies the HasSuffix predicate on the "dependency_type" field.
func DependencyTypeHasSuffix(v string) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldHasSuffix(FieldDependencyType, v))
}

// DependencyTypeEqualFold applies the EqualFold predicate on the "dependency_type" field.
func DependencyTypeEqualFold(v string) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldEqualFold(FieldDependencyType, v))
}

// DependencyTypeContainsFold applies the ContainsFold predicate on the "dependency_type" field.
func DependencyTypeContainsFold(v string) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldContainsFold(FieldDependencyType, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TaskDependency {
	return predicate.TaskDependency(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.TaskDependency {
	return predicate.TaskDependency(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.Task) predicate.TaskDependency {
	return predicate.TaskDependency(func(s *sql.Selector) {
		step := newTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDependsOn applies the HasEdge predicate on the "depends_on" edge.
func HasDependsOn() predicate.TaskDependency {
	return predicate.TaskDependency(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DependsOnTable, DependsOnColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDependsOnWith applies the HasEdge predicate on the "depends_on" edge with a given conditions (other predicates).
func HasDependsOnWith(preds ...predicate.Task) predicate.TaskDependency {
	return predicate.TaskDependency(func(s *sql.Selector) {
		step := newDependsOnStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TaskDependency) predicate.TaskDependency {
	return predicate.TaskDependency(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TaskDependency) predicate.TaskDependency {
	return predicate.TaskDependency(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TaskDependency) predicate.TaskDependency {
	return predicate.TaskDependency(sql.NotPredicates(p))
}
